### ISSUE TITLE
Not compatible with V11 of Foundry.

### ISSUE THREAD

**Issue by Rooksgate** [anvil-vtt/BrokenCompass#70]
Any chance that could be changed? I'm wondering if it's just a version number in the module.

**Comment by PatrickBauer** [comment]
We could try that. You should still be able to install the system though. If you could test that, I'd be happy to bump the version number :)

**Comment by Rooksgate** [comment]
I'd be willing to test.

**Comment by Rooksgate** [comment]
Did you do something? It now works on V11.

**Comment by PatrickBauer** [comment]
@Rooksgate No, nobody changed anything. Foundry produces warnings based on the compatability we set in the system.json file, but that warning doesn't mean that the system won't work :)

**Comment by Rooksgate** [comment]
Well, all I can say is that it wouldn't even install on v11 and now it works.

**Comment by PatrickBauer** [comment]
System works in v11 and v12 now
