### ISSUE TITLE
Probably not compatible with V12 of Foundry

### ISSUE THREAD

**Issue by maciejpa** [anvil-vtt/BrokenCompass#71]
Hi. Probably is problem with Broken Compass on version 12 Foundry. When I create a Actor, I cant open a his datasheet.

**Comment by NerdEyeIndustries** [comment]
yeah I think this ruleset is dead-dead-deadski...

**Comment by PatrickBauer** [comment]
Yes, no one is actively developing this system. But if you're interested in doing so, I'd be more than happy to incorporate your changes to the official repo.

**Comment by maciejpa** [comment]
Hi. I finally managed to sit down and fix the module to make it work properly with Foundry VTT version 12. The required changes need to be made in the system.js file, but I see that it’s almost empty here on GitHub. Could you guide me on which file to modify so that it appears in system.js after installation? Alternatively, how can I share it with you?
My changes can be found at https://github.com/maciejpa/BrokenCompass. The changes that should appear in system.js after installation have been added to the file https://github.com/maciejpa/BrokenCompass/blob/main/system/system.js.

**Comment by PatrickBauer** [comment]
Hey @maciejpa 
The system.js file is generated, thats why that file is so big and pretty convoluted. 

The changes themselves would need to be done in the javascript files that are contained in https://github.com/maciejpa/BrokenCompass/tree/main/src 

These are then built automatically to the system.js file (using webpack)

**Comment by maciejpa** [comment]
Hey @PatrickBauer 
Thanks for your help. I've added "pull requests" for my changes to allow Broken Compass to be played on Foundry VTT version 12.

I hope everything is added correctly. It works fine for me locally.

**Comment by maciejpa** [comment]
Hi @PatrickBauer 
I added another change that ensures correct handling of elements such as Expertise and Scars

**Comment by PatrickBauer** [comment]
Thank you, both are implemented and the system works in v12 now 🙏
